# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet build
  displayName: 'build'

- script: dotnet test $(System.DefaultWorkingDirectory)/**/TestCodeCoverageProject.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  displayName: 'test with coverage'

- task: PublishCodeCoverageResults@1
  displayName: 'publish coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'